### PR TITLE
Configure schema for CLI options

### LINKED ISSUE #40: Warning "type" property
Recently moved up to Serverless 2.40.0 and getting this warning, which will be an error in V3,

Deprecation warning: CLI options definitions were upgraded with "type" property (which could be one of "string", "boolean", "multiple"). Below listed plugins do not predefine type for introduced options:
             - AdditionalStacksPlugin for "skip-additionalstacks", "stack"
            Please report this issue in plugin issue tracker.
            Starting with next major release, this will be communicated with a thrown error.
            More Info: https://www.serverless.com/framework/docs/deprecations/#CLI_OPTIONS_SCHEMA

### PR DESCRIPTION
**Pull request by medikoo**
Fixes https://github.com/nordcloud/serverless-plugin-additional-stacks/issues/40

### CODE REVIEW

**Comment by lhr0909** [comment]
@kennu if you could help merge this, the plugin will potentially continue to work up to v3. This plugin has been super helpful and it is baked into our boilerplate 😄

**Comment by medikoo** [comment]
@kennu great thanks for merging this! Is there a chance to have it published?

**Comment by kennu** [comment]
Thanks for the patch @medikoo . Do you have a view on is there potential to break something, should we publish it as 1.6 or 2.0?

**Comment by medikoo** [comment]
@kennu it's not breaking in any way. For old versions it's just an extra property that will be ignored.

**Comment by kennu** [comment]
Okay, latest version is now published as 1.6.0.

**Comment by medikoo** [comment]
Thank you @kennu !

**Pull request merged**
